services:
  dev_container:
    container_name: zone
    stdin_open: true
    tty: true
    build:
      args:
        CONTAINER_USER: "${DOCKER_USER}"
      dockerfile: ./allinone.Dockerfile.dev
    image: arch:workspace
    volumes:
      - "${HOME}/.ssh:/home/${DOCKER_USER}/.ssh:ro"
      - "${HOME}/projects:/home/${DOCKER_USER}/development:rw"
    ports:
      - "8080:80"
    networks:
      - zone_network

networks:
  zone_network:
    name: zone_network
    driver: bridge
